version: "3.2"

services:
  proxy:
    build: .
    image: ghcr.io/ronoaldo/simpleproxy:latest
    command: --upstream https://content.minetest.net
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - "./data/:/var/cache/proxy"
    environment:
      - ".env"